### ISSUE TITLE
Frequent "EACCES: permission denied" Error

### ISSUE THREAD

**Issue by oliviertassinari** [codesandbox/codesandbox-ci-ui#20]
I would like to raise a potential race condition or a rate-limiting issue with CI as well as a frustration point.

On *mui-org*, we frequently experience failing builds with the following: `EACCES: permission denied`, for instance: https://ci.codesandbox.io/status/mui-org/material-ui-x/pr/890/builds/95536. This seems to be correlated to an increase a build per minute. This happens for us systematically when dependabot opens a bunch of pull requests. The problem is made worse by #11.

**Comment by andrewkmin** [comment]
Hey there, any update on this? Thanks

**Comment by nicitaacom** [comment]
Same error with codesandbox

```
pnpm i next/node
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (/usr/local/share/npm-global/lib/node_modules/pnpm/dist/pnpm.cjs:27828:17)
    at handlePromise (/usr/local/share/npm-global/lib/node_modules/pnpm/dist/pnpm.cjs:28399:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRepoRefs (/usr/local/share/npm-global/lib/node_modules/pnpm/dist/pnpm.cjs:117233:23)
    at async resolveRef (/usr/local/share/npm-global/lib/node_modules/pnpm/dist/pnpm.cjs:117245:20)
    at async resolveGit (/usr/local/share/npm-global/lib/node_modules/pnpm/dist/pnpm.cjs:117196:24)
    at async Object.resolve (/usr/local/share/npm-global/lib/node_modules/pnpm/dist/pnpm.cjs:117495:173)
    at async run (/usr/local/share/npm-global/lib/node_modules/pnpm/dist/pnpm.cjs:129636:23)
Progress: resolved 10, reused 10, downloaded 0, added 0

```
